src/lists/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("<int:list_id>/add_item", views.add_item, name="view_add_item"),
]

src/superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("lists/", include("lists.urls")),
]

src/lists/models.py
from django.db.models.deletion import CASCADE
from django.db import models

# Create your models here.


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default="", on_delete=models.CASCADE)

src/lists/views.py
from typing import Union

from django.db.models.expressions import Combinable
from lists.models import Item, List
from django.http.request import HttpRequest, QueryDict
from django.http.response import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
def home_page(request: HttpRequest) -> HttpResponse:
    return render(request, "home.html")


def view_list(request: HttpRequest, list_id: int) -> HttpResponse:
    list_ = List.objects.get(id=list_id)
    return render(request, "list.html", {"list": list_})


def new_list(request: HttpRequest) -> HttpResponse:
    list_ = List.objects.create()
    Item.objects.create(text=request.POST["item_text"], list=list_)
    return redirect(f"/lists/{list_.id}/")


def add_item(request: HttpRequest, list_id: int) -> HttpResponse:
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=list_)
    return redirect(f"/lists/{list_.id}/")

src/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>To-Do lists</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base.css">
</head>

<body>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col jumbotron">
                <div class="text-center">
                    <h1> {% block header_text %}{% endblock %}</h1>
                    <form method="POST" action=" {% block form_action %}{% endblock %}">
                        <input name="item_text" id="id_new_item" class="form-control input-lg"
                            placeholder="Enter a to-do item" />
                        {% csrf_token %}
                    </form>

                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col">
                {% block table %}
                {% endblock  %}
            </div>
        </div>
    </div>

</body>

</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}



{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock  %}